# Generated by Django 3.0.11 on 2020-11-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=11)),
                ('cpf_respon', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=80)),
                ('data_nasc', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=50)),
                ('num_celular', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=15)),
                ('num_conta', models.CharField(max_length=15)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_id', to='core.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=6)),
                ('descricao', models.CharField(max_length=80)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimento_clientes', to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCriptoativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.CharField(max_length=10)),
                ('data_final', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_clientes', to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=6)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to='core.Investimento')),
                ('tipo_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_operacao', to='core.TipoOperacao')),
            ],
        ),
        migrations.AddField(
            model_name='investimento',
            name='tipo_criptoativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criptoativos', to='core.TipoCriptoativo'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15)),
                ('cpf_funcio', models.CharField(max_length=11)),
                ('nome_funcio', models.CharField(max_length=80)),
                ('rg', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=80)),
                ('filiacao', models.CharField(max_length=80)),
                ('senha', models.CharField(max_length=15)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='core.Cargo')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_id', to='core.Uf'),
        ),
    ]
