# Generated by Django 3.0.11 on 2020-11-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartcontract',
            options={'verbose_name_plural': 'Smart Contracts'},
        ),
    ]
