# Generated by Django 3.0.11 on 2020-11-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201120_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacao',
            options={'verbose_name_plural': 'Smart Contracts'},
        ),
        migrations.AlterModelOptions(
            name='tipooperacao',
            options={'verbose_name_plural': 'Smart Contracts'},
        ),
    ]
